# Get docker for your system @ https://docs.docker.com/get-docker/
#   Docker for Linux
#   Docker Desktop for Windows / macOS
# 
# Use the following commands to start the cluster
#   Starting:
#     $ docker-compose -f docker-compose.yml up
#   Deleteing all ZooKeeper sanpshots:
#     $ docker-compose -f docker-compose.yml down -v
 
version: '2'

services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zoo1.zk.local
    ports:
      - 2181:2181
    volumes:
      - zookeeper1_data:/bitnami
    networks:
      - zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zoo1.zk.local:2888:3888

  zoonavigator:
    image: elkozmon/zoonavigator:1.1.1
    hostname: navigator.zk.local
    ports:
      - 9000:9000
    networks:
      - zookeeper
    environment:
      HTTP_PORT: 9000
      CONNECTION_ZKLOCAL1_NAME: ZooKeeper Server 1
      CONNECTION_ZKLOCAL1_CONN: zoo1.zk.local
      AUTO_CONNECT_CONNECTION_ID: ZKLOCAL1

networks:
  zookeeper:

volumes:
  zookeeper1_data:
    driver: local